import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import NavLink from "./components/NavLink";
import Sidebar from "./components/Sidebar";
import "./globals.css";
import { MessageSquare, Heart, RotateCw } from "lucide-react";
import ConfigureAmplifyClientSide from "@/components/ConfigureAmplify";
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/ui/darkmode-toggle";
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Davis Example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark:bg-black">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)" />
        <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)" />
      </head>
      <body className={`${inter.className} relative`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="fixed top-0 left-0 right-0 bg-white dark:bg-black shadow-md z-50 h-12">
            <div className="px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between h-12">
                <div className="flex items-center">
                  <Sidebar />
                  <Link href="/" className="flex items-center">
                    <Image
                      src="/memeSRC-color.svg"
                      alt="memeSRC Logo"
                      width={24}
                      height={24}
                      className="h-6 w-auto ml-2"
                    />
                    <p className="ml-1 font-semibold text-black dark:text-white">memeSRC</p>
                  </Link>
                </div>
                <div className="flex items-center space-x-4">
                  <NavLink href="/account">
                    Account
                  </NavLink>
                  <ModeToggle />
                </div>
              </div>
            </div>
          </nav>
          <ConfigureAmplifyClientSide />
          <main>{children}</main>
          {/* Action buttons */}
          <div className="fixed bottom-4 left-4 flex space-x-2 z-50">
            <Button size="icon" variant="outline">
              <MessageSquare className="h-4 w-4 text-black dark:text-white" />
            </Button>
            <Button size="icon" variant="outline">
              <Heart className="h-4 w-4 text-black dark:text-white" />
            </Button>
          </div>

          {/* Random button */}
          <div className="fixed bottom-4 right-4 z-50">
            <Button variant="outline" className="text-black dark:text-white">
              <RotateCw className="mr-2 h-4 w-4 text-black dark:text-white" />
              Random
            </Button>
          </div>

          <Toaster position="bottom-right" />
        </ThemeProvider>
      </body>
    </html>
  );
}
