import { Metadata } from 'next';
import SubscriptionPlan from '../components/SubscriptionPlan';

export const metadata: Metadata = {
  title: "Test • memeSRC",
  description: "Generated by create next app",
};

export default function SearchPage() {
  return (
    <div className='mt-20'>
        <SubscriptionPlan />
    </div>
  );
}
